-- alter table current_debts add collateral_usd DOUBLE PRECISION, add profit_usd DOUBLE PRECISION;
-- update current_debts set collateral_usd=collateral_usd_bi::float4/100000000, 
-- profit_usd=profit_usd_bi::float4/100000000;
-- alter table current_debts drop column  collateral_usd_bi, drop column profit_usd_bi;
-- alter table debts add collateral_usd DOUBLE PRECISION, add total_value_usd DOUBLE PRECISION, add profit_usd DOUBLE PRECISION;
-- update debts set collateral_usd=collateral_usd_bi::float4/100000000, 
-- total_value_usd=total_value_usd_bi::float4/100000000,
-- profit_usd=profit_usd_bi::float4/100000000;
-- alter table debts drop column  collateral_usd_bi, drop column total_value_usd_bi, drop column profit_usd_bi;
